### ISSUE TITLE
Send decrypted error report to Elasticsearch

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/error-reporting-service#1]
Require a parser for the decrypted error report that can extract a collection of log events for Logstash to import into Elasticsearch.

It should be possible to create a UUID to group all the log messages together and provide the metadata for the error report (upload timestamp, OS, MultiBit HD version etc).

Elasticsearch API details are here: http://www.elastic.co/guide/en/elasticsearch/client/java-api/1.x/index_.html

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by jim618** [comment]
I've checked that we are seeing error reports from MBHD (built from installer) in the eleastic search UI (tunnelled over SSH).

Closing
