### ISSUE TITLE
Provide backup and restore of error reports in case of ELK failure

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/error-reporting-service#2]
An uploaded error report should be persisted - encrypted - in the event of an ELK failure so that it can be restored at a later date.

**Comment by gary-rowe** [comment]
To verify backup do the following:
1. Start Elasticsearch locally as a foreground task
2. Run up the Error Reporting Service in an IDE in debug mode
3. After successful start put a breakpoint against the `pushToElk()` method in `PublicErrorReportingResource` line 153 (ish)
4. POST the `error-report.json.asc` example to `http://localhost:9191/error-reporting`
5. Observe breakpoint hit then shut down Elasticsearch (CTRL+C) and wait for it to stop
6. Continue execution and observe creation of `/var/error-reporting/error-reports` containing file with UUID
7. Observe 201 CREATED response from service
8. Leave service running and restart Elasticsearch in foreground, wait for complete start
9. POST the `error-report.json.asc` example to `http://localhost:9191/error-reporting`
10. Observe insertion into Elasticsearch

To verify the ingestion (restore) process do the following (can be done immediately after the above):
1. Navigate to `var/error-reporting/error-reports` and observe presence of file with UUID (you can add a bunch of copies using `error-report.json.asc` as the basis
2. Open a shell and execute `curl -X POST http://localhost:9192/tasks/ingest`
3. Observe insertion into Elasticsearch
4. Observe deletion of file(s) as they are ingested
5. Observe "Processing" output from curl (after completion)

Ready for review and close.

**Comment by jim618** [comment]
Worked through the above scenario to check persistence and ingestion of error reports is working fine.
Closing.
