### ISSUE TITLE
Modify startup script to match BRIT service

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/error-reporting-service#3]
Require Linux/Windows variants for completeness.

**Comment by gary-rowe** [comment]
Modified to match BRIT Service (variants, formatting, separator)

Ready for review and close.

**Comment by jim618** [comment]
The start up scripts in master were still referring to 'develop-SNAPSHOT' in the jar so I have updated them. 
Testing the unix script on my Mac.

Awaiting review (especially of Windows script) and closing

**Comment by gary-rowe** [comment]
Pushed a change for both Windows and Linux (one under #4 in error). Didn't see your changes on master, though - did you push?

Ready for review and close.

**Comment by jim618** [comment]
Sorry - just did a merge (seemed identical?) and a push.

Closing.
