### ISSUE TITLE
Add email trigger when an error report is uploaded

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/error-reporting-service#5]
Having an email makes for a convenient reminder that an error report has been uploaded. If traffic gets too high due to scale/duplication then it should be configurable to switch it off.

**Comment by gary-rowe** [comment]
Code has been added but needs testing with an SMTP server.

To verify:
- set system environment variable `SMTP_PASSWORD=<the smtp password>`
- run up the service (no email on error report by default)
- perform a health check and observe health check email
- edit the `config.yml` so that `sendEmails=true`
- send an error report 
- observe email indicating successful receipt of error report

@jim618 Can you take a look at this?

**Comment by jim618** [comment]
Yeah - fastmail has an accessible SMTP server so I can set up a disposable account/ email for that

**Comment by gary-rowe** [comment]
Ready for review and close.

**Comment by gary-rowe** [comment]
Verified working on live. Closing.
